### PR TITLE
Fix/GitHub api

### LINKED ISSUE #12: Empty array failing the result
https://github.com/CircleCI-Public/CircleCI-Env-Inspector/blob/main/index.js#L127
`repo.variables?.length > 0)` still returns an error when `repo.variables` doesn't exist.

### PR DESCRIPTION
**Pull request by KyleTryon**
fixed #12

### CODE REVIEW

**Review by EricRibeiro — APPROVED** [review]

File: run.sh [hunk 1]
```diff
@@ -1,5 +1,12 @@
-#!/usr/bin/env bash
+#!/usr/env/bin bash
```
Comment (afilbert) [inline run.sh:1]: This line is causing `bad interpreter: /usr/env/bin: no such file or directory` for me

Comment (afilbert) [reply run.sh:1]: Reverting it works

Comment (KyleTryon) [reply run.sh]: thank you!
