### PR TITLE
fix: generalize functions, replace recursion with loops and fix bugs

### LINKED ISSUE #2: Node TypeError when running against an organization
When running this against an organization, this produced a node error.

```
...
? Enter your CircleCI API token [hidden]
? Enter your GitHub API token [hidden]
? Select an account fooOrganization
? Is this an Organization (Not a User)? Yes
file:///project/index.js:149
USER_DATA.projects = repoData.filter((repo) => repo.variables.length > 0);
                                                              ^

TypeError: Cannot read properties of undefined (reading 'length')
    at file:///project/index.js:149:63
    at Array.filter (<anonymous>)
    at file:///project/index.js:149:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.3.0
```

### LINKED ISSUE #9: TypeError: Cannot read properties of undefined (reading 'length')
## What

It seems that variables in repoData are sometimes undefined

https://github.com/CircleCI-Public/CircleCI-Env-Inspector/blob/f234e25b5b68d453379ccf14bab34d82ce25aac5/index.js#L136-L149

### Log

```sh
file:///project/index.js:150
USER_DATA.projects = repoData.filter((repo) => repo.variables.length > 0);
                                                              ^

TypeError: Cannot read properties of undefined (reading 'length')
    at file:///project/index.js:150:63
    at Array.filter (<anonymous>)
    at file:///project/index.js:150:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.3.0
```

### PR DESCRIPTION
**Pull request by EricRibeiro**
## Changes

- Replace recursion with loops to avoid stack overflow
- Generalize and extract functions to increase reusability and maintainability
- Implement support for Bitbucket and GitLab via the V1 API
- Create utility functions
- Add error messages in all API requests
- Change the filter to include an [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) (see #2 and #9)

# Issues

- Closes #9 
- Closes #2

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,151 +1,129 @@
...
-  }).then((res) => res.json());
-  return results;
-};
+// Enter GitHub Token if none is set
+const GITHUB_TOKEN = process.env.GITHUB_TOKEN || (await inquirer.prompt([
+  {
+    message: "Enter your GitHub API token",
+    type: "password",
+    name: "ghToken",
+    when: VCS === "GitHub",
```
Comment (KyleTryon) [inline index.js:38]: Nice, didn't know if we could do this

**Review by KyleTryon — APPROVED** [review]
